name=STM32 I3C Controller
version=0.1.0
author=Bahssain Aymane
maintainer=stm32duino
sentence=Arduino-friendly I3C controller for STM32 (H5/U3) with LPS22DF I3C support.
paragraph=Provides a lightweight I3C bus controller class (I3CBus).
category=Communication
url=https://github.com/STMicroelectronics/STM32I3C
architectures=stm32
depends=STM32duino LPS22DF
